[versions]
amecs-api = "1.6.2"
coat = "1.0.0-beta.24"
fabric-api = "0.100.8+1.20.6"
minecraft = "1.20.6"
parchment = "2024.06.16"

[libraries]
amecs-api = { group = "de.siphalor.amecs-api", name = "amecs-api-mc1.20.2", version.ref = "amecs-api" }
coat = { group = "de.siphalor.coat", name = "coat-mc1.20.5", version.ref = "coat" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
