[versions]
coat = "1.0.0-beta.23"
fabric-api = "0.136.0+1.21.10"
minecraft = "1.21.10"
parchment = "2025.10.12"

[libraries]
coat = { group = "de.siphalor.coat", name = "coat-mc1.21.10", version.ref = "coat" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
