[versions]
assertj = "3.26.3"
asm = "9.7"
autoservice = "1.1.1"
java = "8"
jetbrains-annotations = "26.0.1"
junit = "5.11.2"
lombok = "1.18.34"
mockito = "5.14.2"
slf4j = "2.0.16"

[libraries]
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
asm-commons = { group = "org.ow2.asm", name = "asm-commons", version.ref = "asm" }
asm-core = { group = "org.ow2.asm", name = "asm", version.ref = "asm" }
autoservice-annotations = { group = "com.google.auto.service", name = "auto-service-annotations", version.ref = "autoservice" }
autoservice-processor = { group = "com.google.auto.service", name = "auto-service", version.ref = "autoservice" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations" }
junit-platform = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-core = { group = "org.junit.jupiter", name = "junit-jupiter" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4j-rt = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
