[versions]
assertj = "3.26.3"
asm = "9.7"
autoservice = "1.1.1"
acl = "1.3.5"
java-main = "8"
java-test = "21"
jetbrains-annotations = "26.0.1"
jspecify = "1.0.0"
junit = "5.12.0"
lombok = "1.18.34"
mockito = "5.14.2"
slf4j = "2.0.16"

[plugins]
lombok = { id = "io.freefair.lombok", version = "8.13.1" }

[libraries]
acl = { group = "commons-logging", name = "commons-logging", version.ref = "acl" }
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
asm-commons = { group = "org.ow2.asm", name = "asm-commons", version.ref = "asm" }
asm-core = { group = "org.ow2.asm", name = "asm", version.ref = "asm" }
autoservice-annotations = { group = "com.google.auto.service", name = "auto-service-annotations", version.ref = "autoservice" }
autoservice-processor = { group = "com.google.auto.service", name = "auto-service", version.ref = "autoservice" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations" }
jspecify-annotations = { group = "org.jspecify", name = "jspecify", version.ref = "jspecify" }
junit-platform = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-core = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4j-rt = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
