[versions]
amecs-api = "1.6.2"
coat = "1.0.0-beta.24"
fabric-api = "0.87.2+1.19.4"
minecraft = "1.19.4"
parchment = "2023.06.26"

[libraries]
amecs-api = { group = "de.siphalor.amecs-api", name = "amecs-api-mc1.19.4", version.ref = "amecs-api" }
coat = { group = "de.siphalor.coat", name = "coat-mc1.19.4", version.ref = "coat" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
