[versions]
amecs-api = "1.6.2"
coat = "1.0.0-beta.24"
fabric-api = "0.77.0+1.18.2"
minecraft = "1.18.2"
parchment = "2022.11.06"

[libraries]
amecs-api = { group = "de.siphalor.amecs-api", name = "amecs-api-mc1.18.2", version.ref = "amecs-api" }
coat = { group = "de.siphalor.coat", name = "coat-mc1.18.2", version.ref = "coat" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
